export const REGISTER_USER='REGISTER_USER';
export const LOGIN_USER='LOGIN_USER';
export const LOGOUT='LOGOUT';
export const REGISTRATION_FAILED='REGISTRATION_FAILED';
export const LOGIN_FAILED='LOGIN FAILED';
export const LOAD_USER='LOAD_USER';
export const AUTH_ERROR='AUTH_ERROR';